import { useEffect, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Layout from "../Component/Layout";
import { useRouter } from "next/router";


function App() {
  const [data, setData] = useState([]);
  const router = useRouter();
  const dataReceived = router.query;
console.log("dataReceived", dataReceived)
const {title,discription,thumbnail} = dataReceived;


  const fetchData = () => {
    fetch(`https://dummyjson.com/products?limit=10`)
      .then((response) => response.json())
      .then((actualData) => {
        console.log(actualData);
        setData(actualData.products);
        console.log(data);
      })
    
  };

  useEffect(() => {
    fetchData();
  }, []);

  return (
    <Layout>
      <div className={styles.content}>
        <Head>
          <title>GAIA | Products</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>



      
      <div className="bg-white">
        <div className="max-w-2xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
          <h2 className=" text-2xl  tracking-tight  text-slate-400">
            Products
          </h2>

          {title || discription || thumbnail ? (          
           <div class="max-w-sm bg-white border h-full border-gray-200 rounded-lg shadow-md dark:bg-gray-800 dark:border-gray-700">
           <img class="rounded-t-lg h-80"   src={dataReceived.thumbnail}  alt={dataReceived.title}/>
       <div class="p-5">
           <a href="#">
               <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{dataReceived.title}</h5>
           </a>
           <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">{dataReceived.description}</p>
          
           <a href="#" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
           More Details
               <svg aria-hidden="true" class="w-4 h-4 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
           </a>
       </div>
   </div>
          ): (null)
          }


          <div className="  mt-6 grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-2 xl:gap-x-8">
            {data.map((item, index) => (
              <div key={item.id} className="group relative ">
              

<div class="mb-0 max-w-sm bg-white border h-full border-gray-200 rounded-lg shadow-md dark:bg-gray-800 dark:border-gray-700">
        <img class="rounded-t-lg h-80"   src={item.thumbnail}  alt={item.title}/>
    <div class="p-5 ">
        <a href="#">
            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{item.title}</h5>
        </a>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">{item.description}</p>
        <h1 onClick={() => router.push(`/single_product/${item.id}`)} class=" inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
             More Details
            <svg aria-hidden="true" class="w-4 h-4 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </h1>
         
    </div>
</div>

              </div>
            ))}
          </div>
        </div>
      </div>
    </Layout>
  );
}

export default App;



